function plot_percolation_curve(x_vals, res, xlab, titre, eta)
    figure;
    hold on; grid on;

    fill([x_vals fliplr(x_vals)], ...
         [res.Hoeffding_low fliplr(res.Hoeffding_up)], ...
         [0.8 0.8 0.8], ...
         'EdgeColor', 'none', ...
         'FaceAlpha', 0.5, ...
         'DisplayName', 'Intervalle Hoeffding');

    plot(x_vals, res.P_perc_hat, ...
        'LineWidth', 2, ...
        'DisplayName', 'Estimation Monte-Carlo');

    % Nouvelle approximation construite à partir des seuils :
    % - seuil de percolation : point où P ~= 1/2
    % - seuil de connexité   : point où P ~= 1 - epsilon
    if isfield(res, 'P_threshold_approx') && numel(res.P_threshold_approx) == numel(x_vals)
        plot(x_vals, res.P_threshold_approx, '-.', ...
            'LineWidth', 2, ...
            'DisplayName', 'Approx. par seuils');
    end

    plot(x_vals, res.Bound_upper_nonisolated, '--', ...
        'LineWidth', 1.8, ...
        'DisplayName', 'Borne sup. non isolés');

    plot(x_vals, res.Bound_upper_edges, '--', ...
        'LineWidth', 1.8, ...
        'DisplayName', 'Borne sup. arêtes');

    plot(x_vals, res.Bound_upper_tree, '--', ...
        'LineWidth', 1.8, ...
        'DisplayName', 'Borne sup. arbres');

    plot(x_vals, res.Bound_lower_star, ':', ...
        'LineWidth', 2, ...
        'DisplayName', 'Borne inf. étoile');

    xlabel(xlab);
    ylabel('Probabilité');
    title(sprintf(titre, eta));

    legend('show', 'Location', 'southeast');

    ylim([0 1]);
end
